name: gd_fv_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo_gd.png"

flutter_native_splash:
  color: "#0D47A1"
  image: assets/splash.png
  android: true
  ios: false
  web: false
  android_12:
    color: "#0D47A1"
    image: assets/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/catalog/autosolar_catalog.json
    - assets/logo_gd.png
    - assets/splash.png
    - assets/images/
